### ISSUE TITLE
Docker Hubにイメージをプッシュして、docker runで動作するようにする

### ISSUE THREAD

**Issue by chimame** [tsutorm/trend_of_ip#2]
## 課題
現状のままではDocker imageをビルドする必要があるため、起動までにまだ少しだけ手間がかかる。

## 解決案
`docker run`で動作するようにDocker imageをCIにてビルドして、Docker Hubにpushするようにする

**Comment by tsutorm** [comment]
対応したから README.md みて実行してみてちょーだい

**Comment by chimame** [comment]
👍
